"""Shared Pydantic models for Who2Be.

Einzige geteilte Abhaengigkeit zwischen `apps/api` und `apps/mcp`: reine
Pydantic-Modelle, kein I/O. Pro Aggregat ein Schema-Satz (`…Create` /
`…Update` / `…Read` / `…VersionRead`); `…Content` typisiert das `jsonb`-Feld.
"""

from who2be_models.account import AccountDeletionRead, OrganizationDeletionRead
from who2be_models.agent import (
    AgentCopy,
    AgentCreate,
    AgentRead,
    AgentRenderResponse,
    AgentStatus,
    AgentUpdate,
    AgentWithRenderedPrompt,
    RenderFormat,
)
from who2be_models.dashboard import (
    ActivityPagination,
    DashboardActivity,
    DashboardActor,
    DashboardKpis,
    DashboardResponse,
    DashboardStatusDistribution,
    EntityStatusDistribution,
)
from who2be_models.errors import ActionableBy, ApiProblem, ProblemReason
from who2be_models.external_tool import (
    ExternalToolContent,
    ExternalToolCreate,
    ExternalToolRead,
    ExternalToolUpdate,
    ExternalToolVersionRead,
)
from who2be_models.feedback import (
    AgentFeedbackRead,
    FeedbackCreate,
    FeedbackDetailRead,
    FeedbackEntityType,
    FeedbackEvents,
    FeedbackItem,
    FeedbackItemCounts,
    FeedbackItems,
    FeedbackOverview,
    FeedbackOverviewItem,
    FeedbackResolution,
    FeedbackResolutionCreate,
    FeedbackResolutionEvent,
    FeedbackSignal,
    FeedbackSummary,
    FeedbackSummaryItem,
    FeedbackTarget,
    FeedbackUnused,
    FeedbackUnusedItem,
    SystemFeedbackCategory,
    SystemFeedbackCreate,
    UsageEventCreate,
    UsageEventRead,
    UsageOutcome,
)
from who2be_models.invitation import (
    InvitationAccept,
    InvitationCreate,
    InvitationCreated,
    InvitationRead,
)
from who2be_models.links import (
    DeleteBlocked,
    PersonaPlaybookLinkSet,
    PlaybookCompositionLinkSet,
)
from who2be_models.locale import DEFAULT_LOCALE, SUPPORTED_LOCALES, ContentLocale
from who2be_models.me import MeOrganization, MeRead, MeWorkspace
from who2be_models.memory import (
    MEMORY_CONTEXT_MAX_LENGTH,
    MEMORY_FACT_MAX_LENGTH,
    MEMORY_GUARD_PHRASES_MAX,
    MEMORY_MAX_PER_AGENT,
    MEMORY_MIN_IMPORTANCE,
    MEMORY_PERSONA_TOP_N,
    MEMORY_TRIAGE_NOTE_MAX_LENGTH,
    MemoryCategory,
    MemoryCreate,
    MemoryGuardConfig,
    MemoryGuardMode,
    MemoryHit,
    MemoryRead,
    MemoryStatus,
    MemoryTriage,
    MemoryTriageAction,
    MemoryUpdate,
)
from who2be_models.oauth import (
    OAuthClientRegistered,
    OAuthClientRegistration,
    OAuthConsentApprove,
    OAuthConsentResult,
    OAuthError,
    OAuthTokenResponse,
)
from who2be_models.organization import OrganizationCreate, OrganizationRead
from who2be_models.pagination import DEFAULT_LIMIT, MAX_LIMIT, decode_cursor, encode_cursor
from who2be_models.persona import (
    PersonaContent,
    PersonaCreate,
    PersonaMode,
    PersonaRead,
    PersonaUpdate,
    PersonaUsage,
    PersonaVersionContent,
    PersonaVersionRead,
    SkillRef,
)
from who2be_models.placeholder import (
    PlaceholderCatalog,
    PlaceholderInlineExample,
    PlaceholderInlineProps,
    PlaceholderKindInfo,
)
from who2be_models.playbook import (
    PlaybookContent,
    PlaybookCreate,
    PlaybookRead,
    PlaybookRef,
    PlaybookType,
    PlaybookUpdate,
    PlaybookUsage,
    PlaybookVersionRead,
    TriggerOverview,
)
from who2be_models.resource import (
    EmbeddingMode,
    LinkedBlockSection,
    ResourceBlock,
    ResourceBlockAnchor,
    ResourceContent,
    ResourceCreate,
    ResourceLinkItem,
    ResourceLinkRead,
    ResourceLinkSet,
    ResourceRead,
    ResourceRef,
    ResourceUpdate,
    ResourceUsage,
    ResourceVersionRead,
    SubResourceLinkItem,
    SubResourceLinkSet,
    SubResourceRead,
)
from who2be_models.search import ChunkType, ContentChunkHit, SearchHit, SearchType
from who2be_models.status import (
    ALLOWED_TRANSITIONS,
    TRANSITION_RULE_DOC,
    VersionStatus,
    VersionTransitionRequest,
    is_allowed_transition,
)
from who2be_models.status_history import EntityType, StatusHistoryEntry
from who2be_models.system_prompt_template import (
    SystemPromptTemplateContent,
    SystemPromptTemplateCreate,
    SystemPromptTemplateRead,
    SystemPromptTemplateUpdate,
    SystemPromptTemplateVersionRead,
)
from who2be_models.token import TokenCreate, TokenCreated, TokenRead, TokenRename
from who2be_models.tool_policy import (
    AgentCapability,
    AgentToolPolicy,
    MemoryDirective,
    MemoryMode,
    ReadScope,
    TransitionGrant,
)
from who2be_models.tool_requirements import (
    MCP_TOOL_REQUIREMENTS,
    ReadDomain,
    ToolRequirement,
    is_tool_visible,
    is_tool_visible_for,
)
from who2be_models.version_diff import DiffOp, VersionDiff, VersionDiffChange
from who2be_models.whoami import WhoAmIRead
from who2be_models.workspace import WorkspaceCreate, WorkspaceRead, WorkspaceUpdate
from who2be_models.workspace_member import (
    WorkspaceMemberRead,
    WorkspaceMemberUpdate,
    WorkspaceRole,
)

__version__ = "0.1.0"

__all__ = [
    "ALLOWED_TRANSITIONS",
    "TRANSITION_RULE_DOC",
    "AccountDeletionRead",
    "ActionableBy",
    "ActivityPagination",
    "ApiProblem",
    "ChunkType",
    "ContentChunkHit",
    "ContentLocale",
    "DEFAULT_LOCALE",
    "SUPPORTED_LOCALES",
    "AgentCapability",
    "AgentCopy",
    "AgentCreate",
    "AgentRead",
    "AgentRenderResponse",
    "AgentStatus",
    "AgentToolPolicy",
    "AgentUpdate",
    "AgentWithRenderedPrompt",
    "DEFAULT_LIMIT",
    "DashboardActivity",
    "DashboardActor",
    "DashboardKpis",
    "DashboardResponse",
    "DashboardStatusDistribution",
    "DeleteBlocked",
    "DiffOp",
    "EmbeddingMode",
    "EntityStatusDistribution",
    "EntityType",
    "ExternalToolContent",
    "ExternalToolCreate",
    "ExternalToolRead",
    "ExternalToolUpdate",
    "ExternalToolVersionRead",
    "AgentFeedbackRead",
    "FeedbackCreate",
    "FeedbackDetailRead",
    "FeedbackEntityType",
    "FeedbackEvents",
    "FeedbackItem",
    "FeedbackItemCounts",
    "FeedbackItems",
    "FeedbackOverview",
    "FeedbackOverviewItem",
    "FeedbackResolution",
    "FeedbackResolutionCreate",
    "FeedbackResolutionEvent",
    "FeedbackSignal",
    "FeedbackSummary",
    "FeedbackSummaryItem",
    "FeedbackTarget",
    "FeedbackUnused",
    "SystemFeedbackCategory",
    "SystemFeedbackCreate",
    "FeedbackUnusedItem",
    "UsageEventCreate",
    "UsageEventRead",
    "UsageOutcome",
    "SearchHit",
    "SearchType",
    "InvitationAccept",
    "InvitationCreate",
    "InvitationCreated",
    "InvitationRead",
    "LinkedBlockSection",
    "MAX_LIMIT",
    "MCP_TOOL_REQUIREMENTS",
    "MEMORY_CONTEXT_MAX_LENGTH",
    "MEMORY_FACT_MAX_LENGTH",
    "MEMORY_MAX_PER_AGENT",
    "MEMORY_MIN_IMPORTANCE",
    "MEMORY_PERSONA_TOP_N",
    "MEMORY_TRIAGE_NOTE_MAX_LENGTH",
    "MEMORY_GUARD_PHRASES_MAX",
    "MemoryCategory",
    "MemoryCreate",
    "MemoryGuardConfig",
    "MemoryGuardMode",
    "MemoryDirective",
    "MemoryHit",
    "MemoryMode",
    "MemoryRead",
    "MemoryStatus",
    "MemoryTriage",
    "MemoryTriageAction",
    "MemoryUpdate",
    "MeOrganization",
    "MeRead",
    "MeWorkspace",
    "OrganizationCreate",
    "OrganizationRead",
    "PersonaContent",
    "PersonaCreate",
    "PersonaMode",
    "PersonaPlaybookLinkSet",
    "PlaybookCompositionLinkSet",
    "PersonaRead",
    "PersonaUpdate",
    "PersonaUsage",
    "PersonaVersionContent",
    "PersonaVersionRead",
    "SkillRef",
    "PlaceholderCatalog",
    "PlaceholderInlineExample",
    "PlaceholderInlineProps",
    "PlaceholderKindInfo",
    "PlaybookContent",
    "PlaybookCreate",
    "PlaybookRead",
    "PlaybookRef",
    "PlaybookType",
    "PlaybookUpdate",
    "PlaybookUsage",
    "PlaybookVersionRead",
    "ProblemReason",
    "ReadDomain",
    "ReadScope",
    "ResourceBlock",
    "ResourceBlockAnchor",
    "ResourceContent",
    "ResourceCreate",
    "ResourceLinkItem",
    "ResourceLinkRead",
    "ResourceLinkSet",
    "ResourceRead",
    "ResourceRef",
    "ResourceUpdate",
    "ResourceUsage",
    "ResourceVersionRead",
    "SubResourceLinkItem",
    "SubResourceLinkSet",
    "SubResourceRead",
    "RenderFormat",
    "StatusHistoryEntry",
    "SystemPromptTemplateContent",
    "SystemPromptTemplateCreate",
    "SystemPromptTemplateRead",
    "SystemPromptTemplateUpdate",
    "SystemPromptTemplateVersionRead",
    "OAuthClientRegistration",
    "OAuthClientRegistered",
    "OAuthConsentApprove",
    "OAuthConsentResult",
    "OAuthTokenResponse",
    "OAuthError",
    "TokenCreate",
    "TokenCreated",
    "TokenRead",
    "TokenRename",
    "ToolRequirement",
    "TransitionGrant",
    "TriggerOverview",
    "VersionDiff",
    "VersionDiffChange",
    "VersionStatus",
    "VersionTransitionRequest",
    "WhoAmIRead",
    "OrganizationDeletionRead",
    "WorkspaceCreate",
    "WorkspaceMemberRead",
    "WorkspaceMemberUpdate",
    "WorkspaceRead",
    "WorkspaceRole",
    "WorkspaceUpdate",
    "__version__",
    "decode_cursor",
    "encode_cursor",
    "is_allowed_transition",
    "is_tool_visible",
    "is_tool_visible_for",
]
